version: '3.9'

services:

  # mysql service
  mysql:
    image: mysql:latest
    container_name: lemp_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d/
      - ./mysql/data/:/var/lib/mysql/
    ports:
      - 4406:3306
    networks:
      - web_network

  # php service
  php:
    depends_on:
      - mysql
    build: ./php
    container_name: lemp_php
    restart: always
    volumes:
      - ./public_html/:/var/www/html/
    expose:
      - 9000
    networks:
      - web_network

  # nginx service
  nginx:
    depends_on:
      - php
    image: nginx:stable-alpine
    container_name: lemp_nginx
    restart: always
    volumes:
      - ./public_html/:/var/www/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8800:80
    networks:
      - web_network

networks:
  web_network:
    name: lemp_network
    driver: bridge
      